apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-control
spec:
  replicas: 1
  template:
    metadata:
      name: blockchain-control
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared   
        - name: blockchain-config
          configMap:
            name: blockchain-config
        - name: composer-card-store
          persistentVolumeClaim:
          claimName: composer-pvc      
      containers:
      - name: tools
        image: "{{ .Values.tools.image.repository }}:{{ .Values.tools.image.tag }}"
        imagePullPolicy: Always
        command: ["sh", "-c", "
        chmod +x /blockchain-config/setup.sh
        /blockchain-config/setup.sh {{ .Values.tools.profile }}
        trap : TERM INT; sleep infinity & wait"]
        volumeMounts:
        - mountPath: /blockchain-config
          name: blockchain-config        
        - mountPath: /shared
          name: shared    
        - mountPath: /home/composer/.composer
          name: composer-card-store
      - name: peers
        image: "{{ .Values.peer.image.repository }}:{{ .Values.peer.image.tag }}"
        imagePullPolicy: Always
        command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
        volumeMounts:
        - mountPath: /blockchain-config
          name: blockchain-config        
        - mountPath: /shared
          name: shared    
        - mountPath: /home/composer/.composer
          name: composer-card-store
      - name: composer
        image: "{{ .Values.composer.cli.repository }}:{{ .Values.composer.cli.tag }}"
        imagePullPolicy: Always
        command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
        volumeMounts:
        - mountPath: /blockchain-config
          name: blockchain-config        
        - mountPath: /shared
          name: shared    
        - mountPath: /home/composer/.composer
          name: composer-card-store
      restartPolicy: Always

