{{- range $i, $node := .Values.target.orderer.nodes }} 
kind: ConfigMap
apiVersion: v1
metadata:
  name: orderer-env-{{ .name }}-{{ $.Release.Name | lower }}
data:
  ORDERER_CFG_PATH: /data/
  ORDERER_GENERAL_LEDGERTYPE: file
  ORDERER_FILELEDGER_LOCATION: /data/ledger/orderer1
  ORDERER_GENERAL_BATCHTIMEOUT: 1s
  ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT: "10"
  ORDERER_GENERAL_MAXWINDOWSIZE: "1000"
  ORDERER_GENERAL_ORDERERTYPE: {{ $.Values.target.orderer.type }}
  ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
  ORDERER_GENERAL_LISTENPORT: {{ .service.internalPort | quote }}
  ORDERER_GENERAL_LOGLEVEL: debug
  ORDERER_GENERAL_LOCALMSPDIR: /data/ordererOrganizations/{{ $.Values.target.orderer.domain }}/orderers/{{ .name }}.{{ $.Values.target.orderer.domain }}/msp
  ORDERER_GENERAL_LOCALMSPID: {{ $.Values.target.orderer.mspid }}
  ORDERER_GENERAL_GENESISMETHOD: file
  ORDERER_GENERAL_GENESISFILE: /data/orderer.block
  ORDERER_GENERAL_GENESISPROFILE: initial
  ORDERER_GENERAL_TLS_ENABLED: "false"
  GODEBUG: "netdns=go"
---
{{ end }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: orderer-config-{{ .Release.Name | lower }}
data:
  setup.sh: |
{{ include (print .Template.BasePath "/config/_setup.sh.tpl") . | indent 4 }}
  setupMSP.sh: |
{{ include (print .Template.BasePath "/config/_setupMSP.sh.tpl") . | indent 4 }}
  configtx.orderer.yaml: |
{{ include (print .Template.BasePath "/config/_configtx.orderer.yaml.tpl") . | indent 4 }}
  shareFile.sh: |
{{ include (print .Template.BasePath "/config/_shareFile.sh.tpl") . | indent 4 }}
  waitForFile.sh: |
{{ include (print .Template.BasePath "/config/_waitForFile.sh.tpl") . | indent 4 }}
  waitForService.sh: |
{{ include (print .Template.BasePath "/config/_waitForService.sh.tpl") . | indent 4 }}