---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name | lower }}
spec:
  replicas: {{ if eq .Values.target.orderer.type "solo" }}1{{ else }}.Values.target.orderer.replicaCount{{ end }} 
  template:
    metadata:
      labels:
        name: {{ .Release.Name | lower }}
    spec:
      containers:
      - name: orderer
        image: "{{ .Values.images.orderers.repository}}:{{ .Values.images.orderers.tag}}"
        imagePullPolicy: {{.Values.images.orderers.pullPolicy}}
        command: ["sh", "-c", "orderer"]
        envFrom:
        - configMapRef:
            name: orderer-env-{{ .Release.Name | lower }}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /orderer-config
          name: orderer-config
      - name: cli
        image: "{{ .Values.images.tools.repository }}:{{ .Values.images.tools.tag }}"
        imagePullPolicy: {{.Values.images.tools.pullPolicy}}
        command: ["bash", "-c", "sleep 100000"]
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /orderer-config
          name: orderer-config 
      initContainers:
      - name: init-orderer
        image: "{{ .Values.images.tools.repository }}:{{ .Values.images.tools.tag }}"
        imagePullPolicy: {{.Values.images.tools.pullPolicy}}
        command: ["sh", "-c", "chmod +x /orderer-config/setup.sh && /orderer-config/setup.sh"]
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /orderer-config
          name: orderer-config 
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: orderer-pvc-{{ .Release.Name | lower }}
      - name: orderer-config
        configMap:
          name: orderer-config-{{ .Release.Name | lower }}
