apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orderers.service.name }}
  labels:
    run: {{ .Values.orderers.service.name }}
spec:
  type: {{ .Values.orderers.service.type }}
  selector:
    name: orderer
  ports:
  - protocol: TCP
    port: {{ .Values.orderers.service.internalPort }}
    nodePort: {{ .Values.orderers.service.internalPort }}
    name: grpc
