{{- range $i, $node := .Values.target.orderer.nodes }} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  labels:
    run: {{ .service.name }}
spec:
  type: {{ .service.type }}
  selector:
    name: {{ .name }}-{{ $.Release.Name | lower }}
  ports:
  - protocol: TCP
    port: {{ .service.internalPort }}
    nodePort: {{ .service.externalPort }}
    name: grpc
{{ end }}