apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.target.orderer.service.name }}
  labels:
    run: {{ .Values.target.orderer.service.name }}
spec:
  type: {{ .Values.target.orderer.service.type }}
  selector:
    name: {{ .Release.Name | lower }}
  ports:
  - protocol: TCP
    port: {{ .Values.target.orderer.service.internalPort }}
    nodePort: {{ .Values.target.orderer.service.internalPort }}
    name: grpc
