apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ca-{{ .Release.Name | lower }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ca-{{ .Release.Name | lower }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: ca
        image: "{{ .Values.ca.image.repository}}:{{ .Values.ca.image.tag}}"
        command: ["sh", "-c", "fabric-ca-server start -c /ca/cas/ca.yaml"]
        env:
        - name: FABRIC_CA_HOME
          value: /ca/cas
        volumeMounts:
        - mountPath: /ca
          name: ca
        - mountPath: /ca-config
          name: ca-config
      initContainers:
      - name: init-ca
        image: "{{ .Values.ca.image.repository}}:{{ .Values.ca.image.tag}}"
        command: ["sh", "-c", "chmod +x /ca-config/setup.sh && /ca-config/setup.sh"]
        volumeMounts:
        - mountPath: /ca
          name: ca
        - mountPath: /ca-config
          name: ca-config  
      volumes:
      - name: ca
        persistentVolumeClaim:
          claimName: ca-pvc-{{ .Release.Name | lower }}
      - name: ca-config
        configMap:
          name: ca-config-{{ .Release.Name | lower }}