apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ca.main.service.name }}
  labels:
    run: {{ .Values.ca.main.service.name }}
spec:
  type:  {{ .Values.ca.main.service.type }}
  selector:
    name: ca
  ports:
  - protocol: TCP
    port: {{ .Values.ca.main.service.internalPort }}
    nodePort: {{ .Values.ca.main.service.externalPort }}
    name: grpc
