kind: PersistentVolume
apiVersion: v1
metadata:
  name: ca-pv-{{ .Release.Name | lower }}
  labels:
    type: local
    name: ca-{{ .Release.Name | lower }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/ca-{{ .Release.Name | lower }}"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ca-pvc-{{ .Release.Name | lower }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: ca-{{ .Release.Name | lower }}