fabric_version: &fabric_version x86_64-1.1.0-alpha
images:
  tools:
    repository: ldesrosi/fabric-tools-with-ca
    tag: *fabric_version
    pullPolicy: IfNotPresent
  peers:
    repository: ibmblockchain/fabric-peer
    tag: *fabric_version
    pullPolicy: IfNotPresent 
ordererOrganizations: 
  - &targetOrderer
    name: ordererorg
    mspid: OrdererMSP
    domain: example.com
    ca:
      url: network-ca:7054
    service:
      name: blockchain-orderer
      type: NodePort
      externalPort: 31010
      internalPort: 31010  
peerOrganizations:
  - &targetOrg
    name:  Org1
    mspid: Org1MSP
    domain: org1.example.com
    ca:
      url: network-ca:7054
      enrollment_id: ordererorg
      enrollment_password: ordererpw
    nodes:
      - shortName: peer1
        peerType: anchor
        ca:
          url: network-ca:7054
          enrollment_id: ordererorg
          enrollment_password: ordererpw
        service:
          name: blockchain-org1peer1
          type: NodePort
          externalPort: 30110
          internalPort: 30110
          eventInternalPort: 30111
          eventExternalPort: 30111
target:
  orderer: *targetOrderer
  org: *targetOrg
