ca:
  name: org2-ca
  domain: service.org2.consul
  admin: &admin_user org2ca
  password: &admin_password adminpw  
  root:
    hostname: network-ca.service.eu-gb.consul
    port: 30300
  DNs:
    - C: UK
      ST: "Hampshire"
      L: "Hursley"
      O: "IBM"
      OU: "Composer"  
  affiliations:
    - name: org2
      departments:
      - department1
  registrar:
    roles: "peer,client,user,validator,auditor"
    delegatedRoles: "peer,client,user,validator,auditor"
    intermediateCA: true
    revoker: true
    genCRL: true
    attributes: "*"
  identities:
    - name: org2admin
      secret: adminpw
      type: client
      affiliation: org2
      attributes: "\"hf.Registrar.Roles=client\""
    - name: demoAdmin
      secret: adminpw
      type: client
      affiliation: org2
      attributes: "\"hf.Registrar.Roles=client\""
    - name: peer1org2
      secret: adminpw
      type: peer
      affiliation: org2
      attributes: "\"hf.Registrar.Roles=peer\",hf.IntermediateCA=false,hf.Revoker=false"    
    - name: peer2org2
      secret: adminpw
      type: peer
      affiliation: org2
      attributes: "\"hf.Registrar.Roles=peer\",hf.IntermediateCA=false,hf.Revoker=false"
  replicaCount: 1
  service:
    name: org2-ca
    type: NodePort
    externalPort: 30302
    internalPort: 7054  
  sub_cas: