---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: composer-rest-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: composer-rest-server
    spec:
      volumes:
      - name: composer-card-store
        persistentVolumeClaim:
          claimName: composer-pvc
      containers:
      - name: composer-rest-server
        image: "{{ .Values.composer.rest.repository}}:{{ .Values.composer.rest.tag}}"
        imagePullPolicy: {{.Values.composer.rest.pullPolicy}}
        env:
        - name: COMPOSER_CARD
          value: {{.Values.composer.restServerCard}}
        - name: COMPOSER_NAMESPACES
          value: never
        volumeMounts:
        - name: composer-card-store
          mountPath: /home/composer/.composer