---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: composer-playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: composer-playground
    spec:
      volumes:
      - name: shared
        persistentVolumeClaim:
         claimName: shared-pvc
      - name: composer-card-store
        persistentVolumeClaim:
          claimName: composer-pvc
      containers:
      - name: composer-playground
        image:  "{{ .Values.composer.playground.repository}}:{{ .Values.composer.playground.tag}}"
        imagePullPolicy: {{.Values.composer.playground.pullPolicy}}
        volumeMounts:
        - name: composer-card-store
          mountPath: /home/composer/.composer
      initContainers:
      - name: init-playground
        image: busybox
        command: ["sh", "-c", "sleep 1 && while [ ! -f /home/composer/.composer/composer_ready ]; do echo Waiting for composer config; sleep 1; done;"]
        volumeMounts:
        - mountPath: /shared
          name: shared
        - name: composer-card-store
          mountPath: /home/composer/.composer
