fabric_version: &fabric_version 1.0.4
tools:
  image:
    repository: ibmblockchain/fabric-tools
    tag: *fabric_version
    pullPolicy: IfNotPresent
ca:
  image:
    repository: ibmblockchain/fabric-ca
    tag: *fabric_version
    pullPolicy: IfNotPresent
  admin: &admin_user admin
  password: &admin_password adminpw  
  main:
    name: CA
    domain: example.com
    admin: *admin_user
    password: *admin_password
    DNs:
      - C: UK
        ST: "Hampshire"
        L: "Hursley"
        O: "IBM"
        OU: "Composer"  
    affiliations:
      - name: org1
        departments:
        - department1
        - department2
    registrar:
      roles: "peer,orderer,client,user,validator,auditor,ca"
      delegatedRoles: "peer,client,user,validator,auditor"
      intermediateCA: true
      revoker: true
      genCRL: true
      attributes: "*"
    replicaCount: 1
    service:
      name: blockchain-ca
      type: NodePort
      externalPort: 30000
      internalPort: 7054  
    sub_cas:
      - name: CA1
        domain: org1.example.com
        admin: *admin_user
        password: *admin_password
        DNs:
          - C: UK
            ST: "Hampshire"
            L: "Hursley"
            O: "IBM"
            OU: "Composer" 
        affiliations:
          - name: org1
            departments:
            - department1
            - department2
        registrar:
          roles: "peer,client,user,validator,auditor"
          delegatedRoles: "client,user,validator,auditor"
          intermediateCA: true
          revoker: true
          genCRL: true
          attributes: "*"
      - name: CA2
        domain: org2.example.com
        admin: *admin_user
        password: *admin_password  
        DNs:
          - C: UK
            ST: "Hampshire"
            L: "Hursley"
            O: "IBM"
            OU: "Composer" 
        affiliations:
          - name: org2
            departments:
            - department1
            - department2
        registrar:
          roles: "peer,client,user,validator,auditor"
          delegatedRoles: "client,user,validator,auditor"
          intermediateCA: true
          revoker: true
          genCRL: true
          attributes: "*"



