fabric_version: &fabric_version x86_64-1.1.0-alpha
composer_version: &composer_version 0.16.0
images:
  tools:
    repository: ldesrosi/fabric-tools-with-ca
    tag: *fabric_version
    pullPolicy: IfNotPresent
  peers:
    repository: hyperledger/fabric-peer
    tag: *fabric_version
    pullPolicy: IfNotPresent 
  rest:
    repository: hyperledger/composer-rest-server
    tag: *composer_version
    pullPolicy: IfNotPresent
  playground:
    repository: hyperledger/composer-playground
    tag: *composer_version
    pullPolicy: IfNotPresent
redis:
  host: network-store-redis
  password: secretpassword
consortium:
  name: SampleConsortium
  channels:
    - name: SampleChannel
      orgs:
        - Org1
        - Org2
ordererOrganizations:
  - &targetOrderer
    name: ordererorg
    domain: example.com
    mspid: OrdererMSP
    admin_principal: Role.MEMBER 
    ca:
      url: network-ca:7054
      admin:
        enrollment_id: ordereradmin
        enrollment_password: ordererpw
    type: solo
    replicaCount: 1
    nodes: 
      - name: orderer1
        ca:
          url: network-ca:7054
          node: 
            enrollment_id: orderernode
            enrollment_password: ordererpw
        service:
          name: network-orderer
          type: NodePort
          internalPort: 7050
          externalPort: 31010  
    kafka:
      brokers:
        - service:
            name: broker1
            type: NodePort
            externalPort: 36000
            internalPort: 9092
peerOrganizations:
  - name:  Org1
    mspid: Org1MSP
    domain: org1.example.com
    admin_principal: Role.MEMBER 
    ca:
      url: org1-ca:7054
    nodes:
      - shortName: peer1
        peerType: anchor
        ca:
          url: org1-ca:7054
        service:
          name: org1-peer1
          type: NodePort
          internalPort: 7051
          externalPort: 30110
          eventInternalPort: 7053
          eventExternalPort: 30111
  - name: Org2
    mspid: Org2MSP
    domain: org2.example.com
    admin_principal: Role.MEMBER 
    ca:
      url: org2-ca:7054
    nodes:
      - shortName: peer1
        peerType: anchor
        ca:
          url: org2-ca:7054
        service:
          name: org2-peer1
          type: NodePort
          internalPort: 7051
          externalPort: 30210
          eventInternalPort: 7053
          eventExternalPort: 30211
target:
  orderer: *targetOrderer