kind: ConfigMap
apiVersion: v1
metadata:
  name: rest-config-{{ .Release.Name | lower }}
  namespace: default
data:
  setup.sh: |
{{ include (print .Template.BasePath "/config/_setup.sh.tpl") . | indent 4 }}
  waitForService.sh: |
{{ include (print .Template.BasePath "/config/_waitForService.sh.tpl") . | indent 4 }}
  composerProfile.json: |
{{ include (print .Template.BasePath "/config/_composerProfile.json.tpl") . | indent 4 }}