consortium:
  name: SampleConsortium
  channels:
    - name: samplechannel
      orgs:
        - <<: *Org1
          nodes:
            - <<: *Org1Peer1
              endorsingPeer: true
              chaincodeQuery: true
              eventSource: true
        - <<: *Org2
          nodes:
            - <<: *Org2Peer1
              endorsingPeer: true
              chaincodeQuery: true
              eventSource: true
      bnas:
        - name: trade-network
          bna_url: https://github.com/ldesrosi/trading-smart-contract/releases/download/v1.1.0/network.bna
          endorsement_url: https://github.com/ldesrosi/trading-smart-contract/releases/download/v1.1.0/endorsement.json
          admins:
            - id: demoOrg1Admin
              org: *Org1
            - id: demoOrg2Admin
              org: *Org2
ordererOrganizations:
  - &ordererorg
    name: ordererorg
    domain: ordererorg.service.eu-gb.consul
    consul:
      host: bc-service-discovery-ordererorg-consul
      port: 8500
    datacenter: eu-gb
    mspid: OrdererMSP
    admin_principal: Role.MEMBER 
    ca:
      url: network-ca.service.eu-gb.consul:30300
      ref: ordereradmin
    type: solo
    replicaCount: 1
    nodes: 
      - name: orderer1
        ca:
          url: network-ca.service.eu-gb.consul:30300
          ref: orderer
        service:
          name: network-orderer
          type: NodePort
          internalPort: 7050
          externalPort: 30600  
    kafka:
      brokers:
        - service:
            name: broker1
            type: NodePort
            externalPort: 30700
            internalPort: 9092
peerOrganizations:
  - &Org1
    name:  Org1
    mspid: Org1MSP
    domain: org1.service.eu-de.consul
    datacenter: eu-de
    consul:
      host: bc-service-discovery-consul
      port: 8500    
    datacenter: eu-de
    admin_principal: Role.MEMBER 
    ca:
      url: org1-ca.service.eu-de.consul:30301
      ref: org1admin
    nodes:
      - &Org1Peer1
        shortName: peer1org1
        peerType: anchor
        ca:
          url: org1-ca.service.eu-de.consul:30301
          ref: peer1org1
        service:
          name: peer1org1
          type: NodePort
          internalPort: 7051
          externalPort: 31000
          eventInternalPort: 7053
          eventExternalPort: 31100
  - &Org2
    name: Org2
    mspid: Org2MSP
    domain: org2.service.eu-de.consul
    consul:
      host: bc-service-discovery-consul
      port: 8500
    datacenter: eu-de
    admin_principal: Role.MEMBER 
    ca:
      url: org2-ca.service.eu-de.consul:30302
      ref: org2admin
    nodes:
      - &Org2Peer1
        shortName: peer1org2
        peerType: anchor
        ca:
          url: org2-ca.service.eu-de.consul:30302
          ref: peer1org2
        service:
          name: peer1org2
          type: NodePort
          internalPort: 7051
          externalPort: 31001
          eventInternalPort: 7053
          eventExternalPort: 31101
