{{- range .Values.target.org.nodes }} 
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .service.name }}
data:
  CORE_PEER_ID: "{{ .shortName }}.{{ $.Values.target.org.domain }}"
  CORE_PEER_ADDRESS: "{{ .service.name }}:{{ .service.internalPort }}"  
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_LOCALMSPID: "{{ $.Values.target.org.mspid }}"  
  CORE_PEER_MSPCONFIGPATH: "/data/peerOrganizations/{{ $.Values.target.org.domain }}/peers/{{ .shortName }}.{{ $.Values.target.org.domain }}/msp/"
  CORE_PEER_DISCOVERY_PERIOD: "60s"
  CORE_PEER_DISCOVERY_TOUCHPERIOD: "60s"
  CORE_PEER_GOSSIP_ORGLEADER: "false"
  CORE_PEER_GOSSIP_USELEADERELECTION: "true"
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: "{{ .service.name }}:{{ .service.internalPort }}"
  CORE_PEER_COMMITTER_ENABLED: "true"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_TLS_ENABLED: "false"
  CORE_VM_ENDPOINT: "unix:///host/var/run/docker.sock"
  CORE_LOGGING_LEVEL: "debug"
  CORE_LOGGING_GOSSIP: "debug"
  CORE_LOGGING_MSP: "debug"
  CORE_LEDGER_STATE_STATEDATABASE: "goleveldb"
  FABRIC_CFG_PATH: "/etc/hyperledger/fabric/"
  ORDERER_URL: "{{ $.Values.target.orderer.service.name }}:{{ $.Values.target.orderer.service.internalPort }}"
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: peer-config-{{ .Release.Name | lower }}
data:
  setup.sh: |
{{ include (print .Template.BasePath "/config/_setup.sh.tpl") . | indent 4 }}
  setupMSP.sh: |
{{ include (print .Template.BasePath "/config/_setupMSP.sh.tpl") . | indent 4 }}
  configtx.yaml: |
{{ include (print .Template.BasePath "/config/_configtx.yaml.tpl") . | indent 4 }}
  shareFile.sh: |
{{ include (print .Template.BasePath "/config/_shareFile.sh.tpl") . | indent 4 }}
  checkForFile.sh: |
{{ include (print .Template.BasePath "/config/_checkForFile.sh.tpl") . | indent 4 }}
  waitForFile.sh: |
{{ include (print .Template.BasePath "/config/_waitForFile.sh.tpl") . | indent 4 }}
  waitForService.sh: |
{{ include (print .Template.BasePath "/config/_waitForService.sh.tpl") . | indent 4 }}
  createChannel.sh: |
{{ include (print .Template.BasePath "/config/_createChannel.sh.tpl") . | indent 4 }}
  joinChannel.sh: |
{{ include (print .Template.BasePath "/config/_joinChannel.sh.tpl") . | indent 4 }}
  deployComposerRuntime.sh: |
{{ include (print .Template.BasePath "/config/_deployComposerRuntime.sh.tpl") . | indent 4 }}
  deployBNA.sh: |
{{ include (print .Template.BasePath "/config/_deployBNA.sh.tpl") . | indent 4 }}
  processCommands.sh: |
{{ include (print .Template.BasePath "/config/_processCommands.sh.tpl") . | indent 4 }} 
  {{ .Values.target.org.name }}-ConnectionProfile.json: |
{{ include (print .Template.BasePath "/config/_composerProfile.json.tpl") . | indent 4 }}
