{{- range .Values.orgs }}  
{{- $msp := .org.id -}}
{{- $domain := .org.domain -}}
{{- range .org.anchor_peers }} 
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .service.name }}
  namespace: default
data:
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_NETWORKID: nid1
  CORE_PEER_ADDRESS: "{{ .service.name }}:{{ .service.externalPort }}"
  CORE_PEER_LISTENADDRESS: 0.0.0.0:{{ .service.internalPort }}
  CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:{{ .service.eventInternalPort }}
  CORE_PEER_GOSSIP_BOOTSTRAP: "{{ .service.name }}:{{ .service.externalPort }}"
  CORE_PEER_GOSSIP_ORGLEADER: "true"
  CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"
  CORE_PEER_COMMITTER_ENABLED: "true"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
  CORE_PEER_LOCALMSPID: {{ $msp }}
  CORE_PEER_MSPCONFIGPATH: /shared/crypto-config/peerOrganizations/{{ $domain }}/peers/{{.service.shortName }}.{{ $domain }}/msp/
  CORE_LOGGING_LEVEL: debug
  CORE_LOGGING_PEER: debug
  CORE_LOGGING_CAUTHDSL: debug
  CORE_LOGGING_GOSSIP: debug
  CORE_LOGGING_LEDGER: debug
  CORE_LOGGING_MSP: info
  CORE_LOGGING_POLICIES: debug
  CORE_LOGGING_GRPC: debug
  CORE_PEER_TLS_ENABLED: "false"
  CORE_LEDGER_STATE_STATEDATABASE: goleveldb
  FABRIC_CFG_PATH: /etc/hyperledger/fabric/
  ORDERER_URL: "{{ $.Values.orderers.service.name }}:{{ $.Values.orderers.service.externalPort }}"
  GODEBUG: "netdns=go"
{{- end }}
{{- end }} 