{{- range .Values.target.org.nodes }} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  labels:
    run: {{ .service.name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.internalPort }}
      nodePort: {{ .service.externalPort }}
      protocol: TCP
      name: grpc
    - port: {{ .service.eventInternalPort }}
      nodePort: {{ .service.eventExternalPort }}
      protocol: TCP
      name: event      
  selector:
    name: {{ $.Values.target.org.name | lower }}{{ .service.shortName }}
{{- end }}