fabric_version: &fabric_version x86_64-1.1.0-alpha
images:
  tools:
    repository: ldesrosi/fabric-tools-with-ca
    tag: *fabric_version
    pullPolicy: IfNotPresent
  orderers:
    repository: hyperledger/fabric-orderer
    tag: *fabric_version
    pullPolicy: IfNotPresent 
consortium:
  name: SampleConsortium
ordererOrganizations:
  - &targetOrderer
    name: ordererorg
    domain: example.com
    mspid: OrdererMSP
    admin_principal: Role.MEMBER 
    ca:
      url: network-ca:7054
      enrollment_id: ordererorg
      enrollment_password: ordererpw
    type: solo
    replicaCount: 1
    service:
      name: blockchain-orderer
      type: NodePort
      externalPort: 31010
      internalPort: 31010  
    kafka:
      brokers:
        - service:
            name: broker1
            type: NodePort
            externalPort: 36000
            internalPort: 9092
peerOrganizations:
  - name:  Org1
    mspid: Org1MSP
    domain: org1.example.com
    ca:
      url: network-ca:7054
    nodes:
      - shortName: peer1
        peerType: anchor
        ca:
          url: network-ca:7054
        service:
          name: blockchain-org1peer1
          type: NodePort
          externalPort: 30110
          internalPort: 30110
          eventInternalPort: 30111
          eventExternalPort: 30111
  - name: Org2
    mspid: Org2MSP
    domain: org2.example.com
    ca:
      url: network-ca:7054
    nodes:
      - shortName: peer1
        peerType: anchor
        ca:
          url: network-ca:7054
        service:
          name: blockchain-org2peer2
          type: NodePort
          externalPort: 30210
          internalPort: 30210
          eventInternalPort: 30211
          eventExternalPort: 30211
target:
  orderer: *targetOrderer