ca:
  name: network-ca
  domain: service.eu-gb.consul
  admin: &admin_user admin
  password: &admin_password adminpw  
  DNs:
    - C: UK
      ST: "Hampshire"
      L: "Hursley"
      O: "IBM"
      OU: "Composer"  
  affiliations:
    - name: ordererorg
      departments:
      - department1
    - name: org1
      departments:
      - department1
    - name: org2
      departments:
      - department1
      - department2
  registrar:
    roles: "orderer,peer,client,user,validator,auditor,ca"
    delegatedRoles: "orderer,peer,client,user,validator,auditor,ca"
    intermediateCA: true
    revoker: true
    genCRL: true
    attributes: "*"
  identities:
    - name: orderer
      secret: ordererpw
      type: orderer
      affiliation: ordererorg
      attributes: "\"hf.Registrar.Roles=orderer\""
    - name: ordereradmin
      secret: ordererpw
      type: user
      affiliation: ordererorg
      attributes: "\"hf.Registrar.Roles=client\""     
    - name: org1ca
      secret: adminpw
      type: ca
      affiliation: org1
      attributes: "\"hf.Registrar.Roles=peer,client,user,validator,auditor\",hf.IntermediateCA=true,hf.Revoker=true"
    - name: org2ca
      secret: adminpw
      type: ca
      affiliation: org2
      attributes: "\"hf.Registrar.Roles=peer,client,user,validator,auditor\",hf.IntermediateCA=true,hf.Revoker=true"
  replicaCount: 1
  service:
    name: network-ca
    type: NodePort
    externalPort: 30300
    internalPort: 7054  
  sub_cas:
