ca:
  name: org1-ca
  domain: service.org1.consul
  admin: &admin_user org1ca
  password: &admin_password adminpw  
  root:
    hostname: network-ca.service.eu-gb.consul
    port: 30300
  DNs:
    - C: UK
      ST: "Hampshire"
      L: "Hursley"
      O: "IBM"
      OU: "Composer"  
  affiliations:
    - name: org1
      departments:
      - department1
      - department2
  registrar:
    roles: "peer,client,user,validator,auditor"
    delegatedRoles: "peer,client,user,validator,auditor"
    intermediateCA: true
    revoker: true
    genCRL: true
    attributes: "*"
  identities:
    - name: org1admin
      secret: adminpw
      type: client
      affiliation: org1
      attributes: "\"hf.Registrar.Roles=client\""
    - name: demoAdmin
      secret: adminpw
      type: client
      affiliation: org1
      attributes: "\"hf.Registrar.Roles=client\""
    - name: peer1org1
      secret: adminpw
      type: peer
      affiliation: org1
      attributes: "\"hf.Registrar.Roles=peer\",hf.IntermediateCA=false,hf.Revoker=false"
  replicaCount: 1
  service:
    name: org1-ca
    type: NodePort
    externalPort: 30301
    internalPort: 7054  
  sub_cas: