kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-{{ .Values.Component }}-cm"
data:
  INITIAL_CLUSTER_SIZE: {{ default 3 .Values.Replicas | quote }}
  STATEFULSET_NAME: "{{ template "consul.fullname" . }}"
  DNSPORT: "{{ .Values.ConsulDnsPort }}"
  CONSUL_LOCAL_CONFIG: |
    {
        {{- if .Values.uiService.enabled }}
        "ui": true,
        {{- end }} 
        "bind_addr": "0.0.0.0",
        "client_addr": "0.0.0.0",
        "datacenter": "{{ .Values.DatacenterName }}",
        "domain": "{{ .Values.Domain }}",
        "data_dir": "/var/lib/consul",
        "log_level": "INFO",
        "server": true,
        "bootstrap_expect": {{ default 3 .Values.Replicas }},
        "disable_keyring_file": true,
        "leave_on_terminate": false,
        "skip_leave_on_interrupt": true,
        "rejoin_after_leave": true,
        "retry_interval": "30s",
        "ports": {
            "http": {{ .Values.HttpPort }},
            "server": {{ .Values.External.RpcPort }},            
            "dns": {{ .Values.ConsulDnsPort }}, 
            "serf_wan": {{ .Values.External.SerfwanPort }}
        }
    }




